# Generated by Django 4.2.6 on 2023-10-17 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('DENIED', 'Recusado'), ('QUEUED', 'Na fila'), ('STARTED', 'Iniciado'), ('PAUSED', 'Pausado'), ('FINISHED', 'Finalizado'), ('ERROR', 'Erro'), ('CANCELLED', 'Cancelado')], default='QUEUED', max_length=10)),
                ('process_message', models.TextField()),
                ('request_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.FileField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ellapsed_time', models.BigIntegerField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.analysisrequest')),
            ],
        ),
    ]
