# Generated by Django 4.2.6 on 2023-10-17 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TRIAL', 'Versão trial'), ('MONTHLY', 'Plano mensal'), ('ANUAL', 'Plano anual')], default='QUEUED', max_length=10)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_expired', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
